development:
  adapter: postgresql
  encoding: unicode
  database: helpdesk_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: helpdesk_test
  pool: 5
  host: localhost
