development:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: helpdesk_development
  pool: 5
  host: localhost

test:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
